# Generated by Django 5.0.1 on 2024-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=10)),
                ('image', models.FileField(default=None, null=True, upload_to='maingallery')),
            ],
        ),
    ]
