# Generated by Django 4.1.13 on 2024-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maingallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title1', models.CharField(max_length=50)),
                ('imagefilter1', models.CharField(choices=[('Nature', 'Nature'), ('Architect', 'Architect'), ('Preprimary', 'Preprimary')], default='Nature', max_length=20)),
                ('image1', models.ImageField(default=None, null=True, upload_to='maingallerylist/')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='imagefilter',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Architect', 'Architect'), ('Preprimary', 'Preprimary')], default='Nature', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='maingallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_title',
            field=models.CharField(max_length=50),
        ),
    ]
