# Generated by Django 5.0.1 on 2024-02-14 04:55

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_imagefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_title',
            field=models.CharField(max_length=10),
        ),
    ]
