# Generated by Django 5.0.1 on 2024-02-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='./media/maingallery'),
        ),
    ]
