# Generated by Django 5.0.1 on 2024-02-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='imagefilter',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Architect', 'Architect'), ('Preprimary', 'Preprimary')], default='Nature', max_length=20),
        ),
    ]
