# Generated by Django 5.0.1 on 2024-02-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_imagefilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title1', models.CharField(max_length=10)),
                ('imagefilter1', models.CharField(choices=[('Nature', 'Nature'), ('Architect', 'Architect'), ('Preprimary', 'Preprimary')], default='Nature', max_length=20)),
                ('image1', models.FileField(default=None, null=True, upload_to='./media/maingallerylist')),
            ],
        ),
    ]
