# Generated by Django 5.0.1 on 2024-02-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_gallery1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery1',
            new_name='maingallery',
        ),
    ]
