# Generated by Django 5.0.1 on 2024-02-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_rename_gallery1_maingallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='maingallery/'),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='image1',
            field=models.FileField(default=None, null=True, upload_to='maingallerylist/'),
        ),
    ]
