# Generated by Django 4.1.13 on 2024-02-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_gallery_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='maingallery/'),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='image1',
            field=models.ImageField(default=None, null=True, upload_to='maingallerylist/'),
        ),
    ]
