# Generated by Django 4.1.13 on 2024-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_gallery_image_alter_maingallery_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maingallery',
            name='image_title1',
            field=models.CharField(max_length=50),
        ),
    ]
