# Generated by Django 4.1.13 on 2024-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='events/')),
                ('date', models.DateField()),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
