# Generated by Django 5.0.1 on 2024-02-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageabout', models.FileField(default=None, null=True, upload_to='about/')),
            ],
        ),
    ]
