# Generated by Django 4.1.13 on 2024-02-23 07:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    
    ]
