# Generated by Django 5.0.1 on 2024-02-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_title',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
