# Generated by Django 4.1.13 on 2024-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdftitle', models.CharField(max_length=100)),
                ('pdf', models.FileField(default=None, null=True, upload_to='about/')),
            ],
        ),
    ]
